In [19]:
# Description: This file contains the code to generate the mesh of the RRAM.
import math

import matplotlib.pyplot as plt
import numpy as np

from matplotlib.colors import LinearSegmentedColormap
from scipy.constants import Boltzmann, elementary_charge

In [20]:
# # Definir el tamaño del tablero y los valores del mesh (0 o 1)
# filas, columnas = 100, 100
# mesh = np.random.randint(2, size=(filas, columnas))

# # Crear la figura y los ejes
# fig, ax = plt.subplots()

# color_azul = (0, 0, 0)  # azul
# color_verde = (1, 1, 1)  # verde
# color_borde = (1, 1, 0)  # amarillo
# # Iterar a través de los valores del mesh y agregar cuadrados al gráfico
# for i in range(filas):
#     for j in range(columnas):
#         color = color_azul if mesh[i, j] == 1 else color_verde
#         ax.add_patch(plt.Rectangle((j, i), 0.85, 0.85, color=color))

# # Establecer límites de los ejes y ocultar etiquetas
# ax.set_xlim(-0.75, columnas + 0.5)
# ax.set_ylim(-0.5, filas + 0.5)

# # Major ticks every 20, minor ticks every 5
# major_ticks = np.arange(0, columnas, 1)
# minor_ticks = np.arange(0, columnas, 1)

# # ax.set_xticks(major_ticks)
# ax.set_xticks(minor_ticks, minor=True)
# # ax.set_yticks(major_ticks)
# ax.set_yticks(minor_ticks, minor=True)

# # And a corresponding grid
# ax.grid(which="both")

# # Or if you want different settings for the grids:
# ax.grid(which="minor", alpha=1.00)
# ax.grid(which="major", alpha=0.5)

# plt.show()


# # Mostrar el gráfico
# plt.show()

In [21]:
# Generacion de la vacante

# Constantes


t_0 = 10**13  # Hz, en verdad este es el valor de 1/t_0
E_a = 1  # eV
gamma = 3  # Tiene distintos valores dependiendo si el estado es FORMING/SET y RESET
# Valor de la constante de Boltzmann en eV/K
k_b_ev = Boltzmann / elementary_charge

In [22]:
def generation(
    Delta_t, electric_field, temperature, grid_size=0.25e-9, carga_vacante=2
):
    """
    Calculates the generation rate of a certain process.

    Parameters:
    - Delta_t (float): Time step.
    - electric_field (float): Electric field strength in V/m.
    - temperature (float): Temperature in Kelvin.
    - grid_size (float, optional): Size of the grid in meters. Default is 0.25e-9.
    - carga_vacante (int, optional): Vacancy charge. Default is 2.

    Returns:
    - generation_rate (float): The calculated generation rate.
    """
    # TODO: METERLE REESCALADO PARA INTENTAR ENVITAR TRANAAR CON NUMEROS TAN GRANDES Y PEQUEÑOS.
    exponente = (E_a - gamma * grid_size * carga_vacante * carga_vacante *
                 elementary_charge * abs(electric_field)) / (k_b_ev * temperature)
    print(f"El campo eléctrico es: {campo_electrico} V/m")
    print(f"El exponente de la probabilidad es: {exponente}")

    return Delta_t * t_0 * (math.exp(-exponente))


d_t = 0.01
campo_electrico = (1) / (10e-9)
temp = 400  # Kelvin

print(
    f"La probablidad de generacion es: {generation(d_t, campo_electrico, temp)}")

El campo eléctrico es: 100000000.0 V/m
El exponente de la probabilidad es: 29.011295303875205
La probablidad de generacion es: 0.025150958270872183


In [23]:
def initial_state(Eje_x, Eje_y, num_trampas):
    # Crear una matriz de ceros de tamaño Eje_x x Eje_y

    InitialState = np.zeros((Eje_x, Eje_y), dtype=int)

    # Generar 5 posiciones aleatorias para los unos

    posiciones_unos = np.random.choice(
        Eje_x * Eje_y, num_trampas, replace=False)

    # Asignar el valor 1 a las posiciones seleccionadas

    for pos in posiciones_unos:
        fila, columna = divmod(pos, Eje_x)
        InitialState[fila, columna] = 1
    return InitialState

In [24]:
mesh = initial_state(5, 5, 10)
print(mesh)

[[1 1 0 0 1]
 [0 0 0 0 0]
 [1 1 0 1 0]
 [0 0 0 1 1]
 [0 0 1 0 1]]


In [25]:
def DifussiveBehaviour(posicion_x: int, Oxigen_Ion_velocity: float, Simulation_time: float, grid_size=0.25e-9):
    vt = Oxigen_Ion_velocity*Simulation_time
    posicion_x = posicion_x*grid_size

    condiciones = [posicion_x <= vt,
                   (vt < posicion_x) and (posicion_x <= vt + grid_size),
                   (vt + grid_size < posicion_x) and (posicion_x <= vt + 3*grid_size),
                   (posicion_x > vt + 3*grid_size)
                   ]

    funciones = [1, 0.3, 0.1, 0]
    return np.piecewise(posicion_x, condiciones, funciones)


print(DifussiveBehaviour(38, 1, 1))

1.0
